# Generated by Django 4.0 on 2022-04-09 03:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.JSONField(default=dict)),
                ('random_agents', models.PositiveIntegerField()),
                ('random_infected', models.PositiveIntegerField()),
                ('custom', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('value', models.CharField(max_length=7)),
                ('color', models.CharField(max_length=7)),
                ('material', models.CharField(max_length=250, null=True)),
                ('walkable', models.BooleanField(default=True)),
                ('restricted', models.BooleanField(default=True)),
                ('access_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('attack_rate', models.FloatField(default=0.07, validators=[django.core.validators.MinValueValidator(0)])),
                ('infection_rate', models.FloatField(default=0.021, validators=[django.core.validators.MinValueValidator(0)])),
                ('fatality_rate', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('mapfile', models.CharField(max_length=250)),
                ('xy_scale', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(1)])),
                ('t_step', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_iter', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('save_resolution', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('save_verbose', models.BooleanField(default=False)),
                ('terrain', models.ManyToManyField(blank=True, to='api.Terrain')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('prevention', models.JSONField()),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.simulation')),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.virus')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('save_dir', models.CharField(max_length=250, null=True)),
                ('runs', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('parallel', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.scenario')),
                ('agents', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.agentconfig'))
            ],
        ),
    ]
