# Generated by Django 4.0 on 2022-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='config',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='CREATED', max_length=7),
        ),
    ]
