# Generated by Django 4.0 on 2024-03-17 05:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_terrain_interactive_alter_terrain_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='name',
            field=models.CharField(
                default='default-name',
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^[-a-zA-Z0-9_]+\\Z'),
                        'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.',
                        'invalid',
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
