# Generated by Django 4.0 on 2024-03-17 05:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_agentconfig_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfig',
            name='name',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
