# Generated by Django 5.1.5 on 2025-05-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_prevention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='prevention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prevention'),
        ),
    ]
