# Generated by Django 4.0 on 2022-04-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_run_config_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='logfile',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
